### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [TheOriginalTiger/19214-parnachev#1]
1) (-1) * c == (-с)
2) случай  0 0 0 не рассматривается
3) с учетом пункта 2 страшные проверки гвардов лучше переписать на паттерн матчинг

**Comment by preciselyV** [comment]
fixed

**Comment by ankutalev** [comment]
Да где 0 0 0 то ? И 0 0 _ случай потерян

**Comment by preciselyV** [comment]
"случай 0 0 0 не рассматривается" жеж ? Или о чем речь ?
0 0 _ поправил

**Comment by ankutalev** [comment]
Ладно уж, будем считать, что roots 0 0 0 = error "Infinity roots " Вы бы смогли написать. Принято
