### ISSUE TITLE
lab 0 

### ISSUE THREAD

**Issue by ankutalev** [TheOriginalTiger/19214-parnachev#2]
https://github.com/TheOriginalTiger/19214-parnachev/blob/190053bb27afed170711d92b4821abbe8e3f08c2/lists.hs#L35

я кстати совсем забыл, что foldl/ foldr не стандартные функции = ) Перепишите без них, или сделайте свои

**Comment by preciselyV** [comment]
done btw

**Comment by ankutalev** [comment]
принято
